### ISSUE TITLE
Possible enhancement: Deepspeech runtime

### ISSUE THREAD

**Issue by aviweit** [apache/openwhisk-runtime-python#57]
I would like to ask for your opinion on the following deepspeech runtime for deepspeech related actions.

I tried to be consistent with Python AI Action. You can follow "Python 3 DS Action" into the links and the example.

https://github.com/5g-media/incubator-openwhisk-runtime-python/tree/deepspeech

Perhaps it can be contributed aside of Python 3 AI Action or as part of it?

Thanks.

**Comment by rabbah** [comment]
Link is not active.
