### ISSUE TITLE
license for image

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-runtime-python#58]
from the IPMC [release vote](https://lists.apache.org/thread.html/041045024538dd9d3d7bf4b32701260a63996c48e115194302dcf0c1@%3Cgeneral.incubator.apache.org%3E)

there was a question raised about this image:
[../core/python3AiAction/samples/smart-body-crop/fashion-men-1.jpg](https://github.com/apache/incubator-openwhisk-runtime-python/blob/master/core/python3AiAction/samples/smart-body-crop/fashion-men-1.jpg)

- How is this file licensed? Even if is it a “free” license it may have terms around distribution that make it incompatible with the Apache license, and even if not then it still good to list it in LICENSE.

**Comment by rabbah** [comment]
@ddragosd can you comment on the image source?

**Comment by rabbah** [comment]
@ddragosd can you comment on the image source?

**Comment by AngeloDanducci** [comment]
Reverse image search brings up Rene Asmussen as the [source](https://www.pexels.com/photo/full-length-portrait-of-man-standing-in-corridor-325685).

Above link states it's free to use with [this license](https://www.pexels.com/license/) copied below for convenience.

- All photos and videos on Pexels are free to use.
- Attribution is not required. Giving credit to the photographer or Pexels is not necessary but always appreciated.
- You can modify the photos and videos from Pexels. Be creative and edit them as you like.
- Identifiable people may not appear in a bad light or in a way that is offensive.
- Don't sell unaltered copies of a photo or video, e.g. as a poster, print or on a physical product without modifying it first.
- Don't imply endorsement of your product by people or brands on the imagery.
- Don't redistribute or sell the photos and videos on other stock photo or wallpaper platforms.

There is also a [more robust explanation of the license and other terms of service](https://www.pexels.com/terms-of-service/).

**Comment by rabbah** [comment]
Thanks @AngeloDanducci. We can amend the license file accordingly. Looks like we're OK to use it as is / without attribution but we can provide a link.
