### ISSUE TITLE
Naming consistency: "pythonAction" folder/image should include "3" in name

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-runtime-python#60]
The default Python runtime version is  "3" (i.e., v3.6.1); however, the folder it is built under is named:

```/core/pythonAction```

*This is inconsistent with all other runtime naming conventions* which all except this one include (at least the major) language version.  In fact, even within this repo. we follow the naming convention for ```/core/python2``` and ```/code/python3AI```.

**Comment by rabbah** [comment]
I propose removing python action in favor of action loop. We can rename the folders at the same time.

**Comment by rabbah** [comment]
The core folder has:
```
python2ActionLoop  
python3Action      
python3ActionLoop  
python3AiAction    
python3AiActionLoop
```

**Comment by mrutkows** [comment]
@rabbah thanks for closing this old "todo".
