### ISSUE TITLE
Failed to build image for python 2 by "./gradlew :core:python2Action:distDocker"

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk-runtime-python#61]
The error message said python2Action was not found under core, but we actually have it. The Travis job failed at https://travis-ci.org/apache/incubator-openwhisk-runtime-python/builds/532323937?utm_source=github_status&utm_medium=notification.

The command to build python 3 runs well at "./gradlew :core:python3AiAction:distDocker", since we have python3AiAction.

**Comment by houshengbo** [comment]
OK. Python 2 will sunset in probably 6 months, so we decided to not keep python 2 build any more.

**Comment by rabbah** [comment]
This runtime is gone.
