### ISSUE TITLE
Openwhisk incompatibility problem!! 

### ISSUE THREAD

**Issue by pepiparaskev30** [apache/openwhisk-runtime-python#74]
Hello I just find a bug in Openwhisk, when someone creates a zip function containing main.py plus  txt files runs fine - but if the zip contains h5 file, the function hangs. Also I want to say that there are not any other files in zip (just using main.py) and the h5 which affecting the function. The concept is that I created a neural network model (format .h5)with tensorflow and Keras I save it and I made it zip with main.py functions (including docker with ml libraries). When I am trying to invoke the action the OS is not responding and I got none response. Any experience how to handle that?

**Comment by rabbah** [comment]
I don't think this is actionable - one way to debug this is to run the container directly for your runtime:

for example (if your image is called `actionloop-php-v7.3`)
```
> docker run -d -p 8080:8080 actionloop-php-v7.3
> /path/to/openwhisk/tools/actionProxy/invoke.py init your-zip-file.zip
> /path/to/openwhisk/tools/actionProxy/invoke.py run '{"your":"json"}'
```

you can pass parameters from a file - see `invoke.py`'s help.

I hope this helps.
