### ISSUE TITLE
Setting requirements for Python

### ISSUE THREAD

**Issue by berayb** [apache/openwhisk-runtime-python#85]
Hi, 

I'd like to deploy via the REST Api with requirements.txt file. Is that supported for REST Api deployment ? 

Thanks,

**Comment by berayb** [comment]
@sciabarra So as I understand, this update will support requirements.txt as a parameter instead of making zip file ?

**Comment by rabbah** [comment]
@sciabarra is this now supported with the new version of the runtime?

**Comment by sciabarra** [comment]
So the init time is even longer? It is one line of code (if exists requrements.txt pip install -r) in compile if you need it.


-- 
 Michele Sciabarra
github@sciabarra.com



----- Original message -----
