### ISSUE TITLE
convert scripts to python3

### ISSUE THREAD

**Issue by ac427** [apache/openwhisk-runtime-python#87]
looks like most of the scripts run under python2. since python2 is history is there any work in progress to convert them to python3? my python3 scripts can't run as sys.path shows all python2 stuff and if I update it I run into weird issues. 

I will also check if I am make any prs, but would like to know if anyone is working on it?

**Comment by rabbah** [comment]
Hi @ac427.

Which scripts in particular? Scanning the repo for python files, I find the list below.

```
./core/python2ActionLoop/lib/launcher.py
./core/python3Action/pythonrunner.py
./core/python3ActionLoop/lib/launcher.py
./core/python3AiAction/pythonrunner.py
./core/python3AiAction/samples/smart-body-crop/common.py
./core/python3AiAction/samples/smart-body-crop/inference.py
./core/python3AiActionLoop/samples/smart-body-crop/common.py
./core/python3AiActionLoop/samples/smart-body-crop/inference.py
./core/python3AiActionLoop/lib/launcher.py
./tests/src/test/resources/python_virtualenv/__main__.py
./tests/src/test/resources/python_virtualenv_invalid_venv/__main__.py
./tests/src/test/resources/python_virtualenv_invalid_main/mymain.py
```

**Comment by ac427** [comment]
@rabbah , most of the scripts use pip instead of pip3 and also the CMD in Dockerfiles use python instead of python3, that causes lot of issues. (example it can't find any of the python3 modules because of the wrong sys.path  set by the script. )
  
I copied scripts from your repo and created a new docker image for my project.
https://github.com/ac427/ibmfunction_bionic/blob/master/Dockerfile

I will try to create PR later this week in here.

**Comment by dgrove-oss** [comment]
closing as stale
